docs_dir: '.'
site_name: AWS SAA-C03 Certificación
site_description: Apuntes modernos para la certificación de AWS

theme:
  name: material
  language: es
  palette:
    # Configura modo claro y oscuro automático
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro
  features:
    - navigation.tabs       # Barra superior limpia si tienes muchas secciones
    - navigation.sections   # Secciones visuales en la barra lateral
    - search.suggest        # Auto-sugerencias en el buscador
    - search.highlight      # Resalta lo que buscas en el texto