name: Desplegar Notas AWS con Jekyll

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configurar Pages
        uses: actions/configure-pages@v5
      - name: Compilar con Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Subir Web Compilada
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site
      - name: Desplegar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4